# Generated by Django 5.0.7 on 2024-12-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotagging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotaggedimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
