# Generated by Django 5.0.7 on 2024-12-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geotagging', '0003_alter_geotaggedimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotaggedimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
